trigger:

- main

pool: Default

variables:
  BuildConfiguration: release
  
steps:

- task: UseDotNet@2
  displayName: Install .NET 6 sdk
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore Nuget Packages
  inputs:
    command: restore
    projects: '**/WebApp.csproj'

- task: DotNetCoreCLI@2
  displayName: Build Web App
  inputs:
    projects: '**/WebApp.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/*UnitTest*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Create Web App Package (.zip)
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact (WebApp.zip)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(e3b4b040-075f-4ac9-9dc0-89781a968364)'
    appType: 'webApp'
    WebAppName: 'dotnetcore-app-demo'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
    
